version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 285951302175.dkr.ecr.us-east-2.amazonaws.com
  build:
    commands:
      - echo Building Docker image...
      - docker build -t pal-ecr .
      - docker tag pal-ecr:latest 285951302175.dkr.ecr.us-east-2.amazonaws.com/pal-ecr:latest
  post_build:
    commands:
      - echo Pushing to ECR...
      - docker push 285951302175.dkr.ecr.us-east-2.amazonaws.com/pal-ecr:latest
      - echo Writing imagedefinitions.json...
      - printf '[{"name":"pal-container","imageUri":"285951302175.dkr.ecr.us-east-2.amazonaws.com/pal-ecr:latest"}]' > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
